Fix TypeError: (intermediate value).map is not a function
The application has a runtime error: 
TypeError: (intermediate value).map is not a function.
`data` contains a json object, which does not support .map() method.